openapi: 3.0.0
info:
  title: mlapiops
  description: This is the api definition for mlapiops
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/MeMyselfAndI.io/mlapiops/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /predict:
    post:
      summary: post a text to predict sentiment
      operationId: predictSentiment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictSentiment'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: string
                example: positive
components:
  schemas:
    PredictSentiment:
      required:
      - text
      type: object
      properties:
        text:
          type: string
          example: this is a text
